name = "timmylistudio-homepage-auth"
main = "src/index.js"
compatibility_date = "2026-05-17"

[vars]
GITHUB_CLIENT_ID = "Ov23liIyYgCWgS38ySGx"
ADMIN_ORIGIN = "https://timmylistudio.github.io"
ALLOWED_LOGIN = "timmylistudio"
GITHUB_OWNER = "timmylistudio"
GITHUB_REPO = "timmylistudio.github.io"
ANALYTICS_TIMEZONE = "America/New_York"

[[kv_namespaces]]
binding = "ANALYTICS"
id = "8e8fcce35b7c466388478a7641ec44a0"
